name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from release tag
        id: extract_version
        if: github.event_name == 'release'
        run: |
          VERSION=${{ github.ref_name }}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/kasm-playwright-mcp
          docker build -t kasm-playwright-mcp .
          docker tag kasm-playwright-mcp $IMAGE_NAME:${{ env.VERSION }}
          docker tag kasm-playwright-mcp $IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/kasm-playwright-mcp
          docker push $IMAGE_NAME:${{ env.VERSION }}
          docker push $IMAGE_NAME:latest
