services:
  playwright-desktop:
    build: .
    image: playwright-desktop
    container_name: playwright-desktop
    # Set the shared memory size, important for browsers
    shm_size: '2g'
    # Map the necessary ports
    ports:
      - "3000:3000" # For the KasmVNC web desktop
      - "8931:8931" # For the Playwright MCP server
